name: deployment

on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: cypress run --browser chrome
        uses: cypress-io/github-action@v6

      - name: Upload screenshots
        uses: actions/upload-artifact@latest
        if: failure()
           with:
              name: cypress-snapshots
              path: cypress/screenshots*.png    
          