name: deployment

on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: cypress run --browser chrome
        uses: cypress-io/github-action@v6

      - name: Save Screenshots
        uses: action/upload-artifacts@v2
        if: failure()
        with: 
        name: image
        path: cypress/screenshots*.png        